FROM node:24.11.1-alpine3.23 AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY ./ ./
RUN npm run build

FROM node:24.11.1-alpine3.23 AS prod
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --production
COPY --from=build /usr/src/app/dist ./dist
EXPOSE ${PORT}
CMD ["node", "dist/main.js"]